name: update

on:
  push:
  schedule:
    - cron: '0 4 * * *'

jobs:
  update:
    runs-on: ubuntu-latest

    env:
      SANITY_PROJECT_ID: 9omhj7vk
      SANITY_DATASET: production

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: yarn
      - run: yarn workspace @umb/updater start
